### ISSUE TITLE
"paru: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory" when attempting to run paru

### ISSUE THREAD

**Issue by sharjeelmazhar** [Morganamilo/paru#1242]
pacman --version: v7.0.0
libalpm v15.0.0

how to resolve this issue? i am new to arch and i really need to install a package for my work and i cant seem to use paru or yay both

do i need to downgrade something? if, yes then please guide me

**Comment by zegonix** [comment]
i suggest you read one of the last four issues (1238 to 1241)..

**Comment by sharjeelmazhar** [comment]
Okay!

**Comment by jaw-sh** [comment]
This is the leading issue on this repository and the solution is to clone and makepkg the paru-git aur repo.

https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351021340

**Comment by arcolinuxz** [comment]
Could you create a new release as the Arch Linux maintainer is following your release in his package build.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru#n7
Line 7 - version 2.0.3 - release from March - Could you make a new release?

**Comment by hbacelar8** [comment]
Since it is fixed on master, why not just make a release?

**Comment by FeralSmurf** [comment]
> Could you create a new release as the Arch Linux maintainer is following your release in his package build. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru#n7 Line 7 - version 2.0.3 - release from March - Could you make a new release? In the meantime we work with paru-git - last code from github is working on Arch

Wow, the Man himself!!! OMG, I'm so excited to see your post here, Sir. Unfortunately, I gave nothing technical to add to the discussion, just wanted to show my appreciated for all your wonderful work!

**Comment by erwinv** [comment]
> Could you create a new release as the Arch Linux maintainer is following your release in his package build. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=paru#n7 Line 7 - version 2.0.3 - release from March - Could you make a new release? In the meantime we work with paru-git - last code from github is working on Arch

The AUR package maintainer and the Paru author/developer is the same person (Morganamilo) 😄

**Comment by mersenne-twister** [comment]
> Since it is fixed on master, why not just make a release?

Is there any reason this hasn't happened, and the issue was closed? As far as I can tell, the issue still isn't fixed in the latest update; even after pulling this repo running and makepkg, I still have the issue.

**Comment by hbacelar8** [comment]
> > Since it is fixed on master, why not just make a release?
> 
> Is there any reason this hasn't happened, and the issue was closed? As far as I can tell, the issue still isn't fixed in the latest update; even after pulling this repo running and makepkg, I still have the issue.

The issue is closed and a new released has been done. It should work.

**Comment by mersenne-twister** [comment]
> > > Since it is fixed on master, why not just make a release?
> > 
> > 
> > Is there any reason this hasn't happened, and the issue was closed? As far as I can tell, the issue still isn't fixed in the latest update; even after pulling this repo running and makepkg, I still have the issue.
> 
> The issue is closed and a new released has been done. It should work.

I was stupid and ran `makepkg`, running `makepkg -si` fixed the issue. Sorry for the erroneous comment.

**Comment by hbacelar8** [comment]
> I just had the same problem:` paru: error while loading shared libraries: libalpm.so.15: cannot open shared object file: No such file or directory`

What version of libalpm do you have on your system? Run `cd /usr/lib && ls | grep -i alpm` and check the version.

If you have version 14 you should update `core/pacman`.

**Comment by GoddessEyes** [comment]
Same problem 
```
❯ cd /usr/lib && ls | grep -i alpm
libalpm.so
libalpm.so.16
libalpm.so.16.0.1
```

**Comment by debuxxed** [comment]
same

**Comment by ghaziwali** [comment]
yay bin works fine for me

**Comment by SigireddyBalasai** [comment]
Sorry for it I just found this by quick Google search and this is open so I think I can send the message but i went through the all discussions in other issues and found quick fix to download git clone by the paru repo and editing the pkgbuild file
